### ISSUE TITLE
Out of memory when encoding

### ISSUE THREAD

**Issue by chase4646** [tfausak/rattletrap#73] opened 2018-04-14 21:19 UTC
Most of my replays are smaller than 1.2Mb, and I can decode and re-encode with Rattletrap with no problems.

However, a handful are slightly larger (up to 2Mb), and I am unable to encode these due to an out of memory error. Am using Rattletrap on a 2Gb Ubuntu server with virtually nothing else running on it.

Here is an example replay: https://file.io/6HfQKt - the resulting (compact) json is 37Mb and I am unable to re-encode it.

 ```
rattletrap: internal error: Unable to commit 1048576 bytes of memory
     (GHC version 8.2.2 for x86_64_unknown_linux)
         Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
         Aborted
```

**Comment by tfausak** [comment] 2018-04-20 18:46
Ideally Rattletrap would be able to encode large replays without using obscene amounts of memory. I haven't optimized the encoder at all, so there may be some easy ways to speed it up.

**Comment by tfausak** [comment] 2018-08-27 01:29
I added some logging to the test suite to spit out the replay sizes along with how many bytes Rattletrap uses to encode and decode each one. Here are some of the results (all sizes in megabytes):

Replay | Size | Encode | Decode
---| --- | --- | ---
29f5 | 0.021 |   13.804 |    40.111
387f | 0.703 | 1824.233 |  6014.452
2cfe | 1.011 | 2587.766 |  8538.704
3381 | 1.484 | 3884.582 | 12810.813

Looking at just one example, the `3381` replay is about 1.5 MB. It takes 3.9 GB to decode it and 12.8 GB to encode. To put it mildly, those numbers are pretty high. Decoding a replay takes 2,600 times as much memory as the replay itself. Encoding that replay takes 3 times as much memory as that. So decoding a 10 MB replay (the maximum) would take about 25 GB of RAM and encoding it would take an astonishing 84 GB. 

(It's possible that those numbers are inflated a bit. Decoding `3381` with `+RTS -s` reports 927 MB total memory in use. Encoding says 1,794 MB.)

Surprisingly the bloat doesn't seem to be related to laziness. Re-running the tests with `-XStrict` and `-funbox-strict-fields` doesn't substantially change the results. That makes me think that the problem is one of these things: decoding/converting JSON takes a lot of memory, the data types I use aren't space efficient, or the library I'm using for encoding bytes isn't space efficient.

**Comment by tfausak** [comment] 2018-08-27 14:03
Oh, right. My numbers were for _allocations_, but the numbers from GHC's RTS were for _residency_. Decoding a 1.5 MB replay allocates 3.9 GB of RAM, but it uses 927 MB at most at any given time. Both numbers are pretty high, but you shouldn't need 84 GB of RAM to decode a 1.5 MB replay. You'd "only" need about 12 GB for a 10 MB replay.

**Comment by tfausak** [comment] 2019-10-17 22:17
Clearly I have not made any progress on this issue. It would be great if Rattletrap could encode replays without using a ton of memory, but I can't devote the time to make that happen. I'm going to close this issue. If anyone else runs into this problem and wants to take a stab at it, I'd be happy to help out.

**Closed by tfausak** 2019-10-17 22:17 UTC
Labels: bug
