### ISSUE TITLE
Ball Data Not Being Recorded After Goal

### ISSUE THREAD

**Issue by Maverick9320** [tfausak/rattletrap#290] opened 2023-10-04 16:04 UTC
I am trying to get ball data from a replay using the .json file that rattletrap generates. I can successfully extract the data for the location of the ball until a goal is scored. It appears that a new ball is created under a different actor id every time a goal is scored. The new ball actors have no positional data and don't appear in many frames, as far as I can tell. Am I wrong in thinking that these new actor_id's represent the ball? Thanks for any advice you can give me.

**Comment by tfausak** [comment] 2023-10-09 17:33
I think that's the expected behavior. It's been a while since I've poked around with the data. From what I remember, the ball effectively respawns after a goal is scored.

**Comment by Maverick9320** [comment] 2023-10-10 04:46
Yes, but when it respawn's the new balls only appear for 2 seconds or so. 

In every frame I searched the updated actors for the actor ids of the balls. 
actor_ids:
- 'Ball_TA_0' (1786 Frames)
- 'Ball_TA_2' (45 Frames)
- 'Ball_TA_4' (82 Frames)
- 'Ball_TA_6' (46 Frames)

3 goals were scored in this replay which makes sense.

**Comment by tfausak** [comment] 2023-10-11 15:20
Based on https://github.com/nickbabcock/rrrocket/issues/256, I don't think this is a bug with Rattletrap. 

I'd suggest making a very simple replay and stepping through it. Like a 1v0 match where you just drive the ball directly into the goal a few times. 

See #259 for previous discussion about the replay file format.

**Comment by tfausak** [comment] 2023-10-16 14:50
I'm going to close this, but please re-open if it turns out to be an issue with Rattletrap.

**Closed by tfausak** 2023-10-16 14:50 UTC
